# Generated by Django 4.1.5 on 2023-01-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quesion_text',
            new_name='question_text',
        ),
    ]
